<?php


namespace Main\Search\Entity;

use Main\Exception\CollectionTypeViolation;

/**
 * Class Collection
 * @package Main\Search\Entity
 */
class Collection extends \ArrayObject
{
    /**
     * @param mixed $index
     * @param mixed $newval
     */
    public function offsetSet($index, $newval)
    {
        if (!$newval instanceof BaseResult) {
            throw new CollectionTypeViolation("{$newval} is not a " . BaseResult::class . " instance");
        }
        parent::offsetSet($index, $newval); // TODO: Change the autogenerated stub
    }
}