<?php


namespace Main\Search\Entity;

use Main\Exception\CollectionTypeViolation;

class Collection extends \ArrayObject
{
    public function offsetSet($index, $newval)
    {
        if (!$newval instanceof BaseResult) {
            throw new CollectionTypeViolation("{$newval} is not a " . BaseResult::class . " instance");
        }
        parent::offsetSet($index, $newval); // TODO: Change the autogenerated stub
    }
}