<?php

namespace Main\Search\Model;

use Main\Search\Entity\Result;

class FindSubstring extends BaseSearch
{
    public function search(string $string, int $line, string $searchValue): Result
    {
        return parent::search($string, $line, $searchValue); // TODO: Change the autogenerated stub
    }
}